# Building and running a synchronous program for the QUBE rig, whichever program it is.
#
# Both programs in this library -- `FurutaHardware` (swing-up) and `FurutaFriction`
# (constant-velocity friction experiment) -- are purely discrete models that contain their
# own hardware I/O and their own logging, so compiling one and running it is the same job
# twice over: build the model with the analysis' overrides applied, resolve the parameters
# that are to stay runtime-settable, `stkcompile` it, construct the parameter structs behind
# a single world-age boundary, then tick it every `Ts` with the device and the log open.
# What differs is the model constructor, which parameters are tunable, which outputs come
# back and what the log columns mean; all four are arguments here.
#
# The specifics live in codegen.jl (swing-up) and friction.jl (friction experiment), which
# are thin by design: if something in one of them is not about *that* program, it belongs
# here.

using SynchToolkit
using SynchToolkit: ClockedOutput, InputClock, ParametersStruct
import SynchCompiler
import SynchJulia
using ModelingToolkit
using ModelingToolkit: t_nounits as t
using DiscreteComponents: PeriodicClock
using OrderedCollections: OrderedDict

export ProgramLog, ProgramRuntime, run_program!, read_log

# ---------------------------------------------------------------------------
## Runtime-settable parameters
# ---------------------------------------------------------------------------
"""
    resolve_tunables(sys, syms) -> OrderedDict{Symbol, Any}

Resolve the model's own values for the parameters that are to become a runtime-settable
`ParametersStruct`, keyed by the field name each takes in it.

A static `ParametersStruct` (`generated = false`) carries no defaults of its own -- unlike
the autogenerated `AutoPars`, whose field defaults SynchToolkit resolves from the system --
so the values have to be dug out here. `evaluate_varmap!` substitutes the default map into
itself to a fixed point, which is what makes a default that is an expression of other
parameters (`Ni` in terms of `Ti`, say) come out as a number.

Resolution happens against the full pre-partition default map on purpose: an expression
default may reference a parameter that the compiled partition drops, which the partitioned
map no longer has (SynchToolkit#144).

Every symbol handed in must be *unbound* -- a parameter nothing else binds -- or
SynchToolkit rejects the struct. In practice that means a root-level parameter, bound
downwards into the components that use it with Dyad's `final`, which is also what lets an
analysis forward its own value into it.
"""
function resolve_tunables(sys, syms::AbstractDict)
    SymT = ModelingToolkit.SymbolicT
    keysyms = [ModelingToolkit.unwrap(k) for k in keys(syms)]
    dv = Dict{SymT, SymT}(
        ModelingToolkit.default_values(ModelingToolkit.expand_connections(sys)))
    ModelingToolkit.evaluate_varmap!(dv, keysyms)
    out = OrderedDict{Symbol, Any}()
    for (k, field) in syms
        v = Symbolics.value(dv[ModelingToolkit.unwrap(k)])
        out[field] = v isa AbstractArray ?
                     Float64.(vec(collect(Symbolics.value.(v)))) : Float64(v)
    end
    return out
end

# The Dyad compiler turns an analysis' `model = Foo(final x = x)` into a
# `Dict{SymbolicT, SymbolicT}` of un-namespaced model parameter => value, handed to the
# implementation as `spec.overrides`. Translate it into the keyword form the generated model
# constructor takes, so the analysis' parameters reach the model through the model's own
# entry point instead of the implementation reading them back off the spec. Nested paths
# arrive as `a₊b` and become Dyad's `a__b` override syntax.
_model_kwargs(::Nothing) = Dict{Symbol, Any}()
function _model_kwargs(overrides)
    kw = Dict{Symbol, Any}()
    for (k, v) in overrides
        kw[Symbol(replace(string(k), "₊" => "__"))] = Symbolics.value(v)
    end
    return kw
end

# ---------------------------------------------------------------------------
## The log a program writes
# ---------------------------------------------------------------------------
"""
    ProgramLog(file, columns)

Where a program's `DataLogger` writes and what the columns are.

Carried alongside the compiled program because three parties have to agree on it and only
one of them is the model: the component writes the rows, the driver opens the file
([`open_log!`](@ref) needs the header and the column count), and the exported C harness
opens it with the same three values baked into its config header. `file` is what the model
was built with, so it cannot drift from what the program actually writes.
"""
struct ProgramLog
    file::String
    columns::Vector{String}
end

header(l::ProgramLog) = join(l.columns, "\t")
ncols(l::ProgramLog) = length(l.columns)

open_log!(l::ProgramLog) = open_log!(l.file; header = header(l), ncols = ncols(l))

# ---------------------------------------------------------------------------
## Compiling
# ---------------------------------------------------------------------------
"""
    compile_program(ctor; name, Ts, tunables, outputs, log, param_overrides, overrides...)

Compile one of the rig's programs to a SynchJulia node.

  - `ctor` is the generated model constructor (`FurutaHardware`, `FurutaFriction`), called
    with `Ts`, the log file and the overrides.
  - `tunables` maps model parameters to the field names they take in the runtime-settable
    `TuningGains` struct; `outputs` is a function of the un-namespaced system returning the
    signals to expose, in the order the runtime reports them.
  - `log` is the [`ProgramLog`](@ref) the model's `DataLogger` writes.
  - `param_overrides` is an analysis' `spec.overrides`; `overrides...` are Dyad
    `__`-separated model paths, e.g. `control_system__runtime__swingup_catch__gain__k`.

Returns `(; compiled, tuning_struct, auto_struct, tuning_defaults, log, Ts)`, where
`compiled` is SynchToolkit's `CompiledNode` and the two `ParametersStruct`s are kept because
they double as the constructors for the structs they were compiled into. The node's argument
order is `(tick::Bool, gains::TuningGains, auto::AutoPars)`.
"""
function compile_program(ctor; name::Symbol, Ts, tunables::AbstractDict,
                         outputs, log::ProgramLog, param_overrides = nothing,
                         overrides...)
    # Both C libraries the program calls into have to exist before the `:c` backend links
    # them (the Julia backend only needs them at call time).
    ensure_qube_hw()
    ensure_qube_log()
    kw = Dict{Symbol, Any}(overrides)
    merge!(kw, _model_kwargs(param_overrides))
    sys = ctor(; name, Ts, log_file = log.file, kw...)
    # `sys` is the root, so its own name is not part of the flattened symbol names; reach
    # for symbols through the un-namespaced view, which is what `default_values` and
    # `stkcompile` see.
    nsys = ModelingToolkit.toggle_namespacing(sys, false)
    tuning_syms = OrderedDict{Any, Symbol}(
        ModelingToolkit.unwrap(f(nsys)) => field for (f, field) in tunables)
    tuning_defaults = resolve_tunables(sys, tuning_syms)
    tuning_struct = ParametersStruct(; arg_name = :gains, struct_name = :TuningGains,
                                      parameters = tuning_syms, generated = false)
    auto_struct = ParametersStruct(; arg_name = :auto, struct_name = :AutoPars)
    inputs = [InputClock(ModelingToolkit.Clock(Ts)), tuning_struct, auto_struct]
    # Neither `name` nor `clock` may be passed to `ClockedOutput`: `name` desynchronises the
    # declared and assigned Lustre names, and `clock` hits a missing branch in
    # SynchToolkit's `build_output`. So the outputs are indexed positionally.
    outs = [ClockedOutput(o) for o in outputs(nsys)]
    @info "Running stkcompile"
    compiled = SynchToolkit.stkcompile(sys; inputs, outputs = outs)
    return (; compiled, tuning_struct, auto_struct, tuning_defaults, log, Ts = Float64(Ts))
end

# ---------------------------------------------------------------------------
## The runtime
# ---------------------------------------------------------------------------
"""
    ProgramRuntime{names}

A compiled program with its parameter structs, ready to be ticked.

`out = runtime()` advances one step: the program reads the encoders, computes, writes the
motor and appends a row to its log, and `out` is a `NamedTuple` of the node's outputs under
`names`. With `tick = false` the clock does not fire, so no hardware is touched, no row is
logged, and the values are meaningless.

Construct one through [`SwingupController`](@ref) or [`FrictionController`](@ref) rather
than directly; both are this type with their own output names and tuning fields.
"""
struct ProgramRuntime{names, E, G, A}
    exe::E
    gains::G
    auto::A
    log::ProgramLog
    Ts::Float64
end

ProgramRuntime{names}(exe::E, gains::G, auto::A, log, Ts) where {names, E, G, A} =
    ProgramRuntime{names, E, G, A}(exe, gains, auto, log, Float64(Ts))

# A held executable keeps stepping the code it was built with (SynchJulia >= 0.4), so
# `step!`/`reset!` are world-safe from any frame -- no `invokelatest` in the hot path.
function (c::ProgramRuntime{names})(; tick::Bool = true) where {names}
    out = SynchJulia.step!(c.exe, tick, c.gains, c.auto)
    return NamedTuple{names}(values(out))
end

"Resets the program's own state, and the I/O counters and loop timing; the device and the log stay as they are."
function SynchToolkit.reset!(c::ProgramRuntime)
    SynchToolkit.reset!(c.exe)
    reset_hardware_counters!()
    return c
end

log_file(c::ProgramRuntime) = c.log.file

# Construct the `TuningGains`/`AutoPars` parameter objects (with `gains` overriding the
# model's resolved values field by field), optionally build a `SynchExecutable` on `backend`,
# and optionally export the C sources into `export_dir`. These objects are what the runtime
# hands to the node's `step` (as opaque pointers in the C backend); their in-memory field
# bytes are exactly what the exported C reads at its baked-in `fieldoffset`s.
#
# `stkcompile` evaluates a runtime module in a newer world than this frame, but nothing here
# has to know that: a `ParametersStruct` is callable with the `CompiledNode` and
# `SynchExecutable`/`node` take one, and each does its own `invoke_in_world` inside
# (SynchToolkit#159). Hence no `@invokelatest` and no single-crossing contract to honour --
# that used to be this function's whole shape.
function instantiate(gen; gains = (;), backend::Union{Nothing, Symbol} = nothing,
                     export_dir = nothing)
    vals = OrderedDict{Symbol, Any}(gen.tuning_defaults)
    for (field, v) in pairs(gains)
        v === nothing && continue
        haskey(vals, field) ||
            throw(ArgumentError("$field is not one of this program's tunable parameters \
                                 ($(join(keys(vals), ", ")))"))
        vals[field] = vals[field] isa AbstractVector ? collect(float.(v)) : float(v)
    end
    cn = gen.compiled
    g = gen.tuning_struct(cn; vals...)
    # Pass the static struct: AutoPars defaults may be expressions of its fields.
    auto = gen.auto_struct(cn, g)
    exe = backend === nothing ? nothing : SynchJulia.SynchExecutable(cn; backend)
    export_dir === nothing || SynchCompiler.export_c(export_dir, SynchToolkit.node(cn))
    return (; gains = g, auto, exe, SG = typeof(g), AP = typeof(auto))
end

# Build a ready-to-tick runtime from an already-compiled program (avoids recompiling).
function make_runtime(gen, names::Tuple{Vararg{Symbol}}; backend::Symbol = :julia,
                      gains = (;))
    r = instantiate(gen; gains, backend)
    return ProgramRuntime{names}(r.exe, r.gains, r.auto, gen.log, gen.Ts)
end

# ---------------------------------------------------------------------------
## Running it in this process
# ---------------------------------------------------------------------------
"""
    run_program!(ctrl; Tf, arm_deg=0.0, card_options=nothing, mode=:hil)

Tick `ctrl` against the device every `Ts` for `Tf` seconds and return
`(; rows, ticks, log_file, timing)`.

This opens the device and the log, runs the loop, and closes both. It does no logging of its
own -- the program writes the file -- so the loop body is a single call, and `rows` coming
back equal to `ticks` is the check that the program wrote one row per tick. `timing` is
`(; median_dt, max_dt)` of the achieved period, for confirming the loop kept up.

`card_options` overrides the driver's card options (`nothing` keeps `qube_hw.c`'s own
default, `""` leaves the driver on its own). `mode = :callback` runs against whatever
[`bind_hardware!`](@ref) installed, which is how this is exercised without a rig.
"""
function run_program!(ctrl::ProgramRuntime; Tf, arm_deg = 0.0,
                      card_options::Union{Nothing, AbstractString} = nothing,
                      mode::Symbol = :hil)
    Ts = ctrl.Ts
    N = round(Int, Tf / Ts)
    tstamp = Vector{Float64}(undef, N)     # preallocated: GC is disabled below
    n = 0
    SynchToolkit.reset!(ctrl)
    open_log!(ctrl.log)
    open_hardware!(mode; arm_deg, card_options)
    try
        GC.gc()
        GC.enable(false)
        t0 = time()
        t_next = t0 + Ts
        for i in 1:N
            ctrl()
            tstamp[i] = time() - t0
            n = i
            # Absolute schedule rather than "sleep Ts": a step that overruns is absorbed by
            # the next period instead of shifting every period after it. `systemsleep`
            # because `sleep`'s resolution is of the same order as Ts itself.
            dt = t_next - time()
            dt > 0 && Libc.systemsleep(dt)
            t_next += Ts
        end
    catch e
        @error "Terminating run" e
    finally
        # The program cannot unwind a write it has already made, so make sure the motor ends
        # up at zero and the log is flushed whatever happened.
        close_hardware!()
        close_log!()
        GC.enable(true)
    end
    st = log_state()
    st.error && @warn "the log was closed early by a write error" file = st.filename
    dts = n > 1 ? diff(view(tstamp, 1:n)) : Float64[]
    return (; rows = st.rows, ticks = n, log_file = ctrl.log.file,
              timing = (; median_dt = _median(dts),
                          max_dt = isempty(dts) ? NaN : maximum(dts)))
end

# ---------------------------------------------------------------------------
## Reading a log back
# ---------------------------------------------------------------------------
"""
    read_log(path) -> NamedTuple of vectors

Parse a log written by a `DataLogger` inside a program: a tab-separated header line naming
the columns, then one numeric row per tick. Returns a Tables.jl-compatible column table
keyed by the header's names, so it follows whatever columns the program logged rather than a
second copy of the layout kept here.

A row cut short by the run being interrupted is dropped rather than erroring -- the log is
flushed on close, so the last line may be partial.
"""
function read_log(path)
    lines = readlines(path)
    isempty(lines) && throw(ArgumentError("$path is empty"))
    cols = Symbol.(split(strip(lines[1]), '\t'))
    rows = Vector{Vector{Float64}}()
    for l in Iterators.drop(lines, 1)
        isempty(strip(l)) && continue
        vals = tryparse.(Float64, split(strip(l), '\t'))
        (length(vals) == length(cols) && all(!isnothing, vals)) || continue
        push!(rows, Vector{Float64}(vals))
    end
    data = isempty(rows) ? [Float64[] for _ in cols] :
           [[r[j] for r in rows] for j in eachindex(cols)]
    return NamedTuple{Tuple(cols)}(Tuple(data))
end

# Timing of a run recovered from its log, for the targets that do not tick the loop here:
# the program logs the period it achieved, so a fetched log is as good as a local measurement.
function log_timing(path)
    isfile(path) || return (; median_dt = NaN, max_dt = NaN)
    d = try
        read_log(path)
    catch
        return (; median_dt = NaN, max_dt = NaN)
    end
    haskey(d, :dt) && length(d.dt) > 1 || return (; median_dt = NaN, max_dt = NaN)
    # The first row's `dt` has no predecessor and is logged as 0.
    dts = d.dt[2:end]
    return (; median_dt = _median(dts), max_dt = maximum(dts))
end

# Statistics is not a dependency of this package and one median does not justify making it
# one; the achieved periods are a short vector, so sorting a copy costs nothing.
function _median(v)
    isempty(v) && return NaN
    s = sort(collect(v))
    n = length(s)
    return isodd(n) ? s[(n + 1) ÷ 2] : (s[n ÷ 2] + s[n ÷ 2 + 1]) / 2
end
